### ISSUE TITLE
duplicate deviceCodeDic

### ISSUE THREAD

**Issue by vv-takayanagi** [MasamiYamate/YMTGetDeviceName#1]
duplicate deviceCodeDic

"iPad7,11"  :"iPad Pro 10.2inch 7th WiFi",  // iPad Pro 10.2inch 7th Generation WiFi
"iPad7,12"  :"iPad Pro 10.2inch 7th Cell",  // iPad Pro 10.2inch 7th Generation Cellular

"iPad7,11"  :"iPad 7th",                    // iPad 7th Generation WiFi
"iPad7,12"  :"iPad 7th",                    // iPad 7th Generation Cellular

**Comment by MasamiYamate** [comment]
Thanks for pointing out.
It was fixed in version 4.1.
