### ISSUE TITLE
typo "iPod Touch"

### ISSUE THREAD

**Issue by hackenbacker** [MasamiYamate/YMTGetDeviceName#18]
### Description
(en) It should be "**iPod** Touch", but it is "**iPad** Touch".
(ja) "**iPod** Touch"とすべきところ、"**iPad** Touch" になっています。

### Version
5.6.0

### Diff
```diff
581
-            return "iPad Touch (unknown)"
+            return "iPod Touch (unknown)"
```

**Comment by MasamiYamate** [comment]
Thank you for pointing it out! We will release the corrected version over the weekend. 

Thank you for your cooperation!

**Comment by MasamiYamate** [comment]
Closed because it has been resolved
