### ISSUE TITLE
Device generation label

### ISSUE THREAD

**Issue by asamoya** [MasamiYamate/YMTGetDeviceName#5]
Could you please replace "1th" with "1st" since generation name is generally named like first, second, third...
ex) iPhone SE 1th Generation -> iPhone SE 1st Generation

**Comment by MasamiYamate** [comment]
@asamoya Thank you for your advice.
It will be fixed at the same time as the iPhone 13 series is supported.

**Comment by MasamiYamate** [comment]
It was supported by the following merge.
https://github.com/MasamiYamate/YMTGetDeviceName/pull/6
